apiVersion: v1
kind: Secret
metadata:
  name: notification-pipeline-secret
  namespace: notification-pipeline
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: notif_user
  SPRING_DATASOURCE_PASSWORD: notif_pass